# Generated by Django 3.1 on 2020-09-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0003_profile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default='John'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
