# Generated by Django 3.1 on 2020-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0005_auto_20200910_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(blank=True, default='Cuisine', null=True)),
            ],
        ),
    ]
