# Generated by Django 3.1 on 2020-09-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0006_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_name',
            field=models.TextField(default='Cuisine'),
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='Enso.foodcategory')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='Enso.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='food_pref',
            field=models.ManyToManyField(related_name='user_profile', through='Enso.FoodPreferences', to='Enso.FoodCategory'),
        ),
    ]
