# Generated by Django 3.1 on 2020-09-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0007_auto_20200912_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='food_pref',
            new_name='food_categories',
        ),
    ]
