# Generated by Django 3.1 on 2020-09-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0008_auto_20200912_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Enso.profile')),
            ],
        ),
    ]
