# Generated by Django 3.1 on 2020-09-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0009_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='Enso.profile'),
        ),
    ]
