# Generated by Django 3.1 on 2020-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0010_auto_20200913_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.IntegerField(default=1)),
                ('max_points', models.IntegerField(default=1)),
            ],
        ),
    ]
