# Generated by Django 3.1 on 2020-09-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0011_levelsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Enso.levelsystem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
