# Generated by Django 3.1 on 2020-09-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0012_auto_20200913_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('latitude', models.IntegerField(default=1)),
                ('longitude', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(default='user-default-profile-pic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='Enso.zipcode'),
        ),
    ]
