# Generated by Django 3.1 on 2020-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0013_auto_20200914_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='latitude',
            field=models.FloatField(default=1.2789),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='longitude',
            field=models.FloatField(default=103.8536),
        ),
    ]
