# Generated by Django 3.1 on 2020-09-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0014_auto_20200914_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='code',
            new_name='zipcode',
        ),
    ]
