# Generated by Django 3.1 on 2020-09-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0015_auto_20200914_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField()),
                ('address', models.TextField()),
                ('store_image', models.TextField(default='store-default-pic')),
                ('store_menu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('food_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='Enso.foodstore')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
            },
        ),
        migrations.CreateModel(
            name='HawkerCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.TextField()),
                ('region', models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West')], default='n', max_length=1)),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hawker_centre', to='Enso.zipcode')),
            ],
        ),
        migrations.AddField(
            model_name='foodstore',
            name='hawker_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_store', to='Enso.hawkercentre'),
        ),
    ]
