# Generated by Django 3.1 on 2020-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0016_auto_20200917_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore',
            name='cashless_payment',
            field=models.BooleanField(default=False),
        ),
    ]
