# Generated by Django 3.1 on 2020-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0018_hawkercentre_centre_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodstore',
            old_name='address',
            new_name='unit_number',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='address',
            field=models.TextField(default='TEMP'),
        ),
    ]
