# Generated by Django 3.1 on 2020-09-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0021_gathering'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gathering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gathering', to='Enso.gathering')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gathering', to='Enso.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gatherings',
            field=models.ManyToManyField(related_name='user_profile', through='Enso.UserGathering', to='Enso.Gathering'),
        ),
    ]
