# Generated by Django 3.1 on 2020-09-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0022_auto_20200917_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hawkercentre',
            name='region',
        ),
    ]
