# Generated by Django 3.1 on 2020-09-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0023_remove_hawkercentre_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore',
            name='cuisine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_store', to='Enso.foodcategory'),
        ),
    ]
