# Generated by Django 3.1 on 2020-09-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0025_auto_20200919_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('food_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Enso.foodstore')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Enso.profile')),
            ],
        ),
    ]
