# Generated by Django 3.1 on 2020-09-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0027_foodstore_store_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstore',
            name='store_rating',
        ),
    ]
