# Generated by Django 3.1 on 2020-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0030_auto_20200926_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='no_pax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
