# Generated by Django 3.1 on 2020-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0032_usergathering_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='chat_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
