# Generated by Django 3.1 on 2020-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0035_auto_20200927_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
