# Generated by Django 3.1 on 2020-09-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0036_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
    ]
