# Generated by Django 3.1 on 2020-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0037_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
