# Generated by Django 3.1 on 2020-09-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0038_auto_20200927_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': '-date'},
        ),
    ]
