# Generated by Django 3.1 on 2020-09-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0040_auto_20200927_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergathering',
            name='status',
        ),
    ]
