# Generated by Django 3.1 on 2020-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0041_remove_usergathering_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergathering',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('I', 'Invited'), ('J', 'Joined')], default='J', max_length=1),
        ),
    ]
