# Generated by Django 3.1 on 2020-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0042_usergathering_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergathering',
            options={'ordering': ['member_type']},
        ),
        migrations.AddField(
            model_name='usergathering',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
