# Generated by Django 3.1 on 2020-11-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0044_auto_20201105_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergathering',
            name='reviewed',
        ),
    ]
