# Generated by Django 3.1 on 2020-11-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0045_remove_usergathering_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstore',
            name='store_rating',
        ),
    ]
