# Generated by Django 3.1 on 2020-11-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0046_remove_foodstore_store_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore',
            name='store_rating',
            field=models.ManyToManyField(related_name='food_store', through='Enso.Rating', to='Enso.UserGathering'),
        ),
    ]
