# Generated by Django 3.1 on 2020-11-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0047_foodstore_store_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstore',
            name='store_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_gathering',
        ),
        migrations.AddField(
            model_name='usergathering',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gathering', to='Enso.rating'),
        ),
    ]
