# Generated by Django 3.1 on 2020-11-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0048_auto_20201105_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergathering',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gathering', to='Enso.rating'),
        ),
    ]
