# Generated by Django 3.1 on 2020-11-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enso', '0049_auto_20201105_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergathering',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='user_gathering',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Enso.usergathering'),
        ),
    ]
